import {after,test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createServer} from 'vite';
const vite=await createServer({configFile:false,optimizeDeps:{noDiscovery:true,include:[]},server:{middlewareMode:true,watch:null,ws:false},appType:'custom'});after(()=>vite.close());const load=p=>vite.ssrLoadModule(p);
const {analysisSigungu,matchSigungu}=await load('/frontend/services/geography/sigunguRegistry.ts');const {interpretFacility}=await load('/frontend/services/interpretFacility.ts');const {targetPopulationProfile}=await load('/frontend/services/demographics/targetPopulation.ts');const {demographicEngine,percentile}=await load('/frontend/services/demographics/engine.ts');const {normalizeAgePopulation,chooseAgePeriods,selectAgeCodes}=await load('/backend/dataProviders/kosis/agePopulation.ts');const {parseSigunguBoundaries,sigunguLayerValue}=await load('/frontend/services/geography/boundaries/sigungu.ts');const {normalizeChildcareRecord,parseChildcareXml,ChildcareFacilityProvider}=await load('/backend/dataProviders/childcare/ChildcareFacilityProvider.ts');const {aggregateFacilities,demandSupplyIndicators,demandSupplyRelationship,supplyIndicatorPositions,demandSupplyCompatibility}=await load('/frontend/services/dataProviders/facilitySupply.ts');const {buildStructuredProfiles}=await load('/frontend/services/demographics/profiles.ts');const {synthesizeStructuredIssues,structuredPhenomenonGraph}=await load('/frontend/services/issues/structuredIssues.ts');
const profile=await interpretFacility('어린이집'),target=targetPopulationProfile(profile),region=matchSigungu('경기도 용인시 기흥구').region;
// TEST ONLY fixtures model documented fields. No fixture below is an actual LIVE API validation.
const metadata={table:[{TBL_NM:'행정구역(시군구)별/1세별 주민등록인구'}],organization:[],periods:[{PRD_SE:'M',PRD_DE:'202108'},{PRD_SE:'M',PRD_DE:'202308'},{PRD_SE:'M',PRD_DE:'202608'}],units:[{UNIT_NM:'명'}],classifications:[{OBJ_ID:'ITEM',ITM_ID:'TEST-TOTAL',ITM_NM:'총인구수'},{OBJ_ID:'REGION',OBJ_ID_SN:'1',ITM_ID:'TEST-GU',ITM_NM:'기흥구',UP_ITM_ID:'TEST-CITY'},{OBJ_ID:'REGION',OBJ_ID_SN:'1',ITM_ID:'TEST-CITY',ITM_NM:'용인시',UP_ITM_ID:'TEST-SIDO'},{OBJ_ID:'REGION',OBJ_ID_SN:'1',ITM_ID:'TEST-SIDO',ITM_NM:'경기도'},{OBJ_ID:'AGE',OBJ_ID_SN:'2',ITM_ID:'TEST-ALL',ITM_NM:'계'},...Array.from({length:100},(_,n)=>({OBJ_ID:'AGE',OBJ_ID_SN:'2',ITM_ID:`TEST-AGE-${n}`,ITM_NM:`${n}세`})),{OBJ_ID:'AGE',OBJ_ID_SN:'2',ITM_ID:'TEST-100+',ITM_NM:'100세 이상'}]};
const row=(age,period='202608',patch={})=>({ORG_ID:'101',TBL_ID:'DT_1B04006',TBL_NM:metadata.table[0].TBL_NM,ITM_ID:'TEST-TOTAL',ITM_NM:'총인구수',C1:'TEST-GU',C1_NM:'기흥구',C2:age===null?'TEST-ALL':`TEST-AGE-${age}`,C2_NM:age===null?'계':`${age}세`,PRD_SE:'M',PRD_DE:period,UNIT_NM:'명',DT:age===null?'1000':'10',...patch});
const cells=(period='202608')=>[row(null,period),...Array.from({length:6},(_,n)=>row(n,period))];
const normalize=rows=>normalizeAgePopulation(rows,metadata,target,'2026-09-21T00:00:00Z',['202108','202608'],'M');
const metrics=normalize([...cells('202108'),...cells()]);
const fixture=(patch={})=>normalizeChildcareRecord({stcode:'TEST-FACILITY-1',crname:'TEST ONLY 어린이집',sidoname:'경기도',sigunguname:'용인시 기흥구',crstatusname:'정상',crcapat:'100',crchcnt:'60',datastdrdt:'20260831',...patch},'2026-09-21T00:00:00Z');
test('canonical registry has unique leaf units and preserves nested city district',()=>{assert.equal(analysisSigungu.length,256);assert.equal(new Set(analysisSigungu.map(r=>r.regionCode)).size,256);assert.equal(region.regionCode,'41463');assert.equal(region.parentCityCode,'41460');assert.equal(region.parentSidoCode,'41');assert.equal(matchSigungu('중구').status,'AMBIGUOUS');assert.equal(matchSigungu('서울특별시 중구').region.regionCode,'11140');assert.equal(matchSigungu('경기도 용인시기흥구').region.regionCode,'41463');assert.ok(!analysisSigungu.some(r=>r.regionCode==='41460'));});
test('facility changes reuse one explicit-age definition engine',async()=>{const senior=targetPopulationProfile(await interpretFacility('노인복지관'));const seniorAlias=targetPopulationProfile(await interpretFacility('노인복지시설'));const youth=targetPopulationProfile(await interpretFacility('청소년 문화시설'));const library=targetPopulationProfile(await interpretFacility('도서관'));assert.deepEqual(target.ageRanges.map(a=>[a.minAge,a.maxAge]),[[0,5]]);assert.deepEqual(senior.ageRanges.map(a=>[a.minAge,a.maxAge]),[[65,null]]);assert.deepEqual(seniorAlias.ageRanges,senior.ageRanges);assert.deepEqual(youth.ageRanges.map(a=>[a.minAge,a.maxAge]),[[9,24]]);assert.equal(library.primaryGroup,'GENERAL_POPULATION');assert.equal(selectAgeCodes(metadata,senior).selected.length,36);assert.equal(selectAgeCodes(metadata,youth).selected.length,16);});
test('age cells normalize exactly; raw records and formula inputs retained',()=>{const p=metrics.find(m=>m.metricType==='TARGET_POPULATION');assert.equal(p.value,60);assert.equal(p.regionCode,'41463');assert.equal(p.administrativeLevel,'SIGUNGU');assert.equal(p.derivation.inputMetricIds.length,6);assert.equal(p.structuredSource.rawSource.records.length,6);assert.equal(p.structuredSource.tableId,'DT_1B04006');});
test('missing age data and missing history are never filled',()=>{const partial=normalize(cells().slice(0,-1));assert.equal(partial.find(m=>m.metricType==='TARGET_POPULATION').value,null);const result=demographicEngine(partial,target,'live');assert.equal(result.regions.find(r=>r.region.regionCode==='41463').status,'PARTIAL');assert.ok(result.coverage.missing>0);assert.deepEqual(chooseAgePeriods({...metadata,periods:[{PRD_SE:'M',PRD_DE:'202608'}]}).periods,['202608']);assert.deepEqual(chooseAgePeriods({...metadata,periods:metadata.periods.slice(1)}).periods,['202308','202608']);});
test('same-period share works; unknown historical boundaries and zero denominator prohibit rates',()=>{let result=demographicEngine(metrics,target,'live');let r=result.regions.find(r=>r.region.regionCode==='41463');assert.equal(r.metrics.find(m=>m.metricType==='TARGET_POPULATION_SHARE').value,.06);assert.ok(!r.metrics.some(m=>m.metricType==='TARGET_POPULATION_CHANGE'));const known=metrics.map(m=>({...m,boundaryVersion:'TEST-VERIFIED',value:m.referenceDate==='2021-08'&&m.metricType==='TARGET_POPULATION'?0:m.value}));r=demographicEngine(known,target,'live').regions.find(r=>r.region.regionCode==='41463');assert.ok(r.metrics.some(m=>m.metricType==='TARGET_POPULATION_CHANGE'));assert.ok(!r.metrics.some(m=>m.metricType==='TARGET_POPULATION_CHANGE_RATE'));});
test('SIDO/national cannot become direct SIGUNGU evidence; wrong periods rejected',()=>{const broad=normalize(cells().map(r=>({...r,C1:'TEST-SIDO',C1_NM:'경기도'})));assert.ok(broad.every(m=>m.administrativeLevel==='SIDO'&&m.regionCode===null));assert.equal(demographicEngine(broad,target,'live').coverage.missing,256);assert.throws(()=>normalize(cells().map(r=>({...r,PRD_DE:'209901'}))));});
test('percentiles are tie-aware positions in comparable cohorts, never need scores',()=>{assert.ok(Math.abs(percentile(10,[10,20,30])-100/6)<1e-12,'percentile should match the expected midrank within floating-point tolerance');assert.equal(percentile(10,[10,10]),50);assert.equal(percentile(10,[10]),null);const other=metrics.map(m=>({...m,regionCode:'11140',regionId:'sigungu:11140',metricId:`other:${m.metricId}`}));const result=demographicEngine([...metrics,...other],target,'live');assert.ok(result.cohorts.some(c=>c.count===2));const mixed=other.map(m=>({...m,unit:'천명'}));const mixedResult=demographicEngine([...metrics,...mixed],target,'live');assert.deepEqual(mixedResult.cohorts.map(c=>c.metric),['TARGET_POPULATION_SHARE']);assert.equal(mixedResult.cohorts[0].count,2);});
test('DEMO never contributes to demographics, profiles, map layers',()=>{assert.equal(demographicEngine(metrics,target,'demo').coverage.missing,256);const demo=metrics.map(m=>({...m,dataMode:'DEMO'}));assert.equal(demographicEngine(demo,target,'live').coverage.missing,256);const result=demographicEngine(metrics,target,'live');const profiles=buildStructuredProfiles(result,[],'live');assert.equal(sigunguLayerValue(profiles.find(p=>p.region.regionCode==='41463'),'TARGET_POPULATION'),60);assert.equal(sigunguLayerValue({...profiles[0],mode:'demo'},'TARGET_POPULATION'),null);assert.ok(profiles.every(p=>p.candidateScore===null));});
test('real geometry joins all 256 canonical codes; missing metrics render NO DATA',async()=>{const data=parseSigunguBoundaries(JSON.parse(await readFile('data/geography/sigungu/korea_sigungu.geojson','utf8')));assert.equal(data.features.length,256);assert.equal(sigunguLayerValue(undefined,'FACILITY_COUNT'),null);assert.throws(()=>parseSigunguBoundaries({type:'FeatureCollection',features:[{type:'Feature',properties:{regionCode:'FAKE'}}]}));});
test('official facility response fields normalize without replacing null with zero',()=>{const r=fixture();assert.equal(r.regionCode,'41463');assert.equal(r.capacity,100);assert.equal(r.currentUsers,60);assert.equal(r.referenceDate,'2026-08-31');assert.equal(fixture({crcapat:''}).capacity,null);assert.equal(fixture({crcapat:'0'}).capacity,0);assert.equal(fixture({sidoname:'',sigunguname:'중구'}).normalizationStatus,'UNRESOLVED');assert.equal(fixture({crabldt:'20200101'}).status,'CLOSED');});
test('XML parser reads documented flat records and rejects entities/API failures',()=>{const rows=parseChildcareXml('<response><item><stcode>TEST</stcode><crname>A &amp; B</crname><Crcapat>20</Crcapat></item></response>');assert.equal(rows[0].crcapat,'20');assert.equal(rows[0].crname,'A & B');for(const xml of ['<!DOCTYPE x><response></response>','<response><errcode>INFO-100</errcode></response>','<response></response>'])assert.throws(()=>parseChildcareXml(xml));});
test('closed/suspended excluded, duplicate IDs counted once; conflicts and incomplete capacity remain MISSING',()=>{const a=fixture();let result=aggregateFacilities([a,a,fixture({stcode:'CLOSED',crabldt:'20200101'}),fixture({stcode:'PAUSE',crstatusname:'휴지'})],'41463');assert.equal(result.metrics.find(m=>m.metricType==='FACILITY_COUNT').value,1);assert.equal(result.quality.duplicateRecords,1);assert.equal(result.quality.excludedRecordCount,3);assert.equal(result.metrics.find(m=>m.metricType==='UTILIZATION_RATE').value,60);result=aggregateFacilities([a,fixture({stcode:'B',crcapat:''})],'41463');assert.equal(result.metrics.find(m=>m.metricType==='TOTAL_CAPACITY').value,null);assert.equal(result.metrics.find(m=>m.metricType==='FACILITY_COUNT').value,2);assert.equal(aggregateFacilities([a,fixture({crcapat:'101'})],'41463').quality.conflictingDuplicates,1);});
test('unknown status, unresolved geography and mixed dates prohibit complete aggregation',()=>{for(const bad of [{crstatusname:''},{sidoname:'',sigunguname:'중구'},{datastdrdt:'20250901'}]){const result=aggregateFacilities([fixture(),fixture({stcode:'B',...bad})],'41463');assert.equal(result.metrics.find(m=>m.metricType==='FACILITY_COUNT').value,null);}});
test('ratios require exact dates/region/units and valid positive denominators',()=>{const p={...metrics.find(m=>m.metricType==='TARGET_POPULATION'&&m.referenceDate==='2026-08'),referenceDate:'2026-08-31'};const supply=aggregateFacilities([fixture()],'41463').metrics;const indicators=demandSupplyIndicators(p,supply);assert.equal(indicators.length,4);assert.ok(indicators.every(i=>i.inputMetricIds.length===2&&i.sourceUrls.length===2));assert.equal(demandSupplyIndicators({...p,referenceDate:'2026-08'},supply).length,0);assert.equal(demandSupplyIndicators({...p,regionCode:'11140'},supply).length,0);assert.equal(demandSupplyIndicators({...p,dataMode:'DEMO'},supply).length,0);assert.equal(demandSupplyIndicators(p,supply.map(m=>({...m,dataMode:'DEMO'}))).length,0);assert.ok(demandSupplyIndicators({...p,value:0},supply).every(i=>!i.type.includes('PER_1000')));});
test('opposing and parallel change relationships preserved; synthesis asks questions, never forces construction',()=>{const demand={...metrics.find(m=>m.metricType==='TARGET_POPULATION'),referenceDate:'2021-08-31',boundaryVersion:'TEST-SAME',value:100};const supply=aggregateFacilities([fixture()],'41463').metrics.find(m=>m.metricType==='TOTAL_CAPACITY');const s0={...supply,referenceDate:'2021-08-31',value:100};const d1={...demand,referenceDate:'2026-08-31',value:110};assert.equal(demandSupplyRelationship(demand,d1,s0,{...supply,value:90}).type,'SUPPLY_DEMAND_DIVERGENCE');assert.equal(demandSupplyRelationship(demand,d1,s0,{...supply,value:120}).type,'SUPPLY_GROWTH_WITH_DEMAND_GROWTH');assert.equal(demandSupplyRelationship(demand,{...d1,value:90},s0,{...supply,value:100}).type,'POSSIBLE_OVERSUPPLY');const r=demandSupplyRelationship(demand,d1,s0,{...supply,value:90});const base=buildStructuredProfiles(demographicEngine(metrics,target,'live'),[],'live').find(p=>p.region.regionCode==='41463');const issues=synthesizeStructuredIssues([{...base,demandSupplyRelationships:[r]}]);assert.equal(issues.length,1);const graph=structuredPhenomenonGraph({...base,demandSupplyRelationships:[r]});assert.equal(graph.phenomena.length,2);assert.equal(graph.relationships[0].relationshipType,r.type);assert.deepEqual(graph.issues[0].phenomenonIds,graph.phenomena.map(p=>p.id));assert.match(issues[0].architecturalRelevance,/처방하지 않습니다/);});
test('facility provider missing key does not call network; independent cached regional requests',async()=>{await assert.rejects(new ChildcareFacilityProvider('').getFacilities('41463'),e=>e.code==='MISSING_KEY');let calls=0;const provider=new ChildcareFacilityProvider('TEST-KEY',async url=>{calls++;assert.equal(url.searchParams.get('arcode'),'41463');assert.equal(url.protocol,'https:');return new Response('<response><item><stcode>TEST</stcode><sidoname>경기도</sidoname><sigunguname>용인시 기흥구</sigunguname><crstatusname>정상</crstatusname><crcapat>10</crcapat><crchcnt>5</crchcnt><datastdrdt>20260831</datastdrdt></item></response>');});await Promise.all([provider.getFacilitySupplyMetrics('41463'),provider.getFacilitySupplyMetrics('41463')]);assert.equal(calls,1);assert.deepEqual(await provider.getAvailablePeriods(),[]);});
test('profile integration keeps demand-only, supply-only and missing states visible',()=>{const demo=demographicEngine([],target,'live');const result=buildStructuredProfiles(demo,[aggregateFacilities([fixture()],'41463')],'live');assert.equal(result.find(p=>p.region.regionCode==='41463').facilityDataCoverage.status,'SUPPLY_ONLY');assert.equal(sigunguLayerValue(result.find(p=>p.region.regionCode==='41463'),'FACILITY_COUNT'),1);assert.ok(result.every(p=>p.candidateScore===null));assert.equal(buildStructuredProfiles(demo,[aggregateFacilities([fixture()],'41463')],'demo').find(p=>p.region.regionCode==='41463').facilitySupplyMetrics.length,0);});

test('supply cohorts preserve traceability and exclude different definitions, periods, duplicates and DEMO',()=>{
 const demand={...metrics.find(m=>m.metricType==='TARGET_POPULATION'),referenceDate:'2026-08-31'};
 const first=demandSupplyIndicators(demand,aggregateFacilities([fixture()],'41463').metrics);
 const second=first.map(i=>({...i,id:`second:${i.id}`,regionCode:'11140',value:i.value*2}));
 const positions=supplyIndicatorPositions([...first,...second]);assert.equal(positions.length,8);assert.ok(positions.every(p=>p.cohortSize===2));assert.equal(positions[0].percentile,25);
 assert.ok(first.every(i=>i.sourceIds.length&&i.targetDefinition&&i.facilityDefinition));
 for(const patch of [{dataMode:'DEMO'},{targetDefinition:'OTHER'},{facilityDefinition:'OTHER'},{referenceDate:'2025-08-31'}])assert.equal(supplyIndicatorPositions([...first,...second.map(i=>({...i,...patch}))]).length,0);
 assert.equal(supplyIndicatorPositions([...first,...first]).length,0);
 const profile={...buildStructuredProfiles(demographicEngine([],target,'live'),[],'live').find(p=>p.region.regionCode==='41463'),demandSupplyIndicators:first};assert.equal(sigunguLayerValue(profile,'CAPACITY_PER_1000_TARGET_POPULATION'),first.find(i=>i.type==='CAPACITY_PER_1000_TARGET_POPULATION').value);
});
test('quality exposes missing rates and compatibility exposes temporal and denominator limitations',()=>{
 const supply=aggregateFacilities([fixture(),fixture({stcode:'B',crcapat:'',crchcnt:''})],'41463');assert.equal(supply.quality.missingCapacityRate,.5);assert.equal(supply.quality.missingCurrentUsersRate,.5);assert.equal(supply.quality.referenceDateCoverage,1);assert.equal(supply.quality.activeStatusCoverage,1);
 const d={...metrics.find(m=>m.metricType==='TARGET_POPULATION'),referenceDate:'2026-08-31'};const sm=aggregateFacilities([fixture()],'41463').metrics;
 assert.equal(demandSupplyCompatibility(d,sm).status,'COMPATIBLE');assert.equal(demandSupplyCompatibility(undefined,sm).status,'UNKNOWN');assert.match(demandSupplyCompatibility({...d,referenceDate:'2021-08'},sm).reasons.join(' '),/기준일 불일치/);assert.equal(demandSupplyIndicators({...d,value:Infinity},sm).length,0);
});
test('generic aggregation accepts an explicit future provider definition without treating daycare as that facility',()=>{
 const definition={facilityType:'TEST-LIBRARY',provider:'TEST-PROVIDER',dataset:'TEST',sourceUrl:'https://example.org/test',activeDefinition:'TEST active definition'};
 const result=aggregateFacilities([{...fixture(),facilityType:definition.facilityType,provider:definition.provider}],'41463',true,definition);assert.equal(result.metrics[0].value,1);assert.equal(result.metrics[0].facilityType,'TEST-LIBRARY');assert.equal(result.provider,'TEST-PROVIDER');
});
