import {EvidenceType} from '../../../frontend/evidenceTypes';
import {plainText} from '../../../frontend/services/evidence/evidenceNormalizer';
import type {RawSearchResult,SearchProvider} from '../../../frontend/services/evidence/types';
import {ProviderError} from './webSearchProvider';
const organization=(host:string)=>host.endsWith('pyeongtaek.go.kr')?'평택시':host.endsWith('gg.go.kr')||host.endsWith('gyeonggi.go.kr')?'경기도':host;
const excluded=/(^|\.)(naver\.com|naver\.net|pstatic\.net|w3\.org)$/i;
const decode=(value:string)=>value.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'");
export function parsePublicWebResults(html:string,retrievedAt=new Date().toISOString()):RawSearchResult[]{const rows:RawSearchResult[]=[],seen=new Set<string>();for(const match of html.matchAll(/<a\b[^>]*href=["'](https?:\/\/[^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const raw=decode(match[1]);let url:URL;try{url=new URL(raw);}catch{continue;}if(excluded.test(url.hostname)||seen.has(url.href))continue;const fileName=url.searchParams.get('user_file_nm'),fallback=decodeURIComponent(fileName??url.pathname.split('/').at(-1)??url.hostname);const title=(fileName?fallback:plainText(match[2])||fallback).replace(/새 창 열림$/g,'').trim();if(!title||title.length<4)continue;seen.add(url.href);const official=/\.(?:go|or|ac)\.kr$/i.test(url.hostname);rows.push({title,url:url.href,snippet:title,sourceOrganization:organization(url.hostname),sourceLabel:'공개 웹 검색',publishedDate:null,providerDateHint:null,retrievedAt,provider:'public-web',mode:'live',retrievalStatus:'SEARCH_RESULT_ONLY',authors:[],sourceType:official?'LOCAL_REPORT':'OTHER',sourceAuthority:official?'LOCAL_GOVERNMENT':'OTHER'});}return rows;}
export function createPublicWebProvider(fetcher:typeof fetch=fetch):SearchProvider{return{id:'public-web',mode:'live',categories:[EvidenceType.RESEARCH],configured:true,maxQueriesPerSearch:3,async search(query,signal){const endpoint=new URL('https://search.naver.com/search.naver');endpoint.searchParams.set('query',query.query);let response:Response;try{response=await fetcher(endpoint,{signal:AbortSignal.any([signal,AbortSignal.timeout(10000)]),headers:{Accept:'text/html','User-Agent':'Mozilla/5.0 (compatible; facility-need-finder/0.1; university prototype)'}});}catch{throw new ProviderError('NETWORK');}if(response.status===429)throw new ProviderError('RATE_LIMIT');if(!response.ok)throw new ProviderError('NETWORK');return parsePublicWebResults(await response.text()).slice(0,query.maxResults);}};}
