import type {FacilityProfile} from '../../evidenceTypes';
import type {DemographicMetric,TargetPopulationProfile} from '../demographics/types';
import type {RegionalFacilitySupply} from './facilityNeed';

export type SelectionIndicator={indicator:string;role:'DEMAND'|'SUPPLY'|'CONTEXT';reason:string;source:string|null;referencePeriod:string|null;geographicResolution:'SIGUNGU'|'UNKNOWN';coverage:number;status:'VERIFIED'|'PARTIAL'|'UNAVAILABLE';proxyStrength?:'DIRECT'|'INDIRECT'};
export interface FacilitySelectionBasis {facility:string;planningQuestion:string;demandDimensions:string[];supplyDimensions:string[];mismatchHypotheses:string[];selectedIndicators:SelectionIndicator[];rejectedIndicators:SelectionIndicator[];missingIndicators:string[];selectionRules:string[];limitations:string[];status:'VALID'|'INSUFFICIENT_SELECTION_BASIS'}

const unavailable=(indicator:string,role:SelectionIndicator['role'],reason:string):SelectionIndicator=>({indicator,role,reason,source:null,referencePeriod:null,geographicResolution:'UNKNOWN',coverage:0,status:'UNAVAILABLE'});
export function buildFacilitySelectionBasis(profile:FacilityProfile,target:TargetPopulationProfile,metrics:DemographicMetric[]=[],supply:RegionalFacilitySupply[]=[]):FacilitySelectionBasis{
 const verifiedMetrics=metrics.filter(row=>row.metricType==='TARGET_POPULATION'&&row.dataMode==='LIVE'&&row.verification==='source_verified'&&row.administrativeLevel==='SIGUNGU'&&row.value!==null&&!!row.referenceDate);
 const supplyRows=supply.filter(row=>row.verificationStatus!=='UNKNOWN'&&(row.supplyValue!==undefined||row.facilityCount!==null));const referencePeriod=verifiedMetrics.map(row=>row.referenceDate).filter(Boolean).sort().at(-1)??null;
 const early=target.primaryGroup==='EARLY_CHILDHOOD',youth=target.primaryGroup==='YOUTH',senior=target.primaryGroup==='OLDER_ADULTS',library=profile.facilityName==='도서관';
 const directLabel=early?'0–5세 인구':youth?'9–24세 인구':senior?'65세 이상 인구':null;const selected:SelectionIndicator[]=[];const rejected:SelectionIndicator[]=[];const missing:string[]=[];
 if(directLabel){const found=verifiedMetrics.length>1;const reason=early?'어린이집의 직접 이용 대상 연령인 만 0–5세 잠재 인구 규모를 나타냅니다.':youth?'청소년 문화시설의 법정 청소년 연령 범위와 연결되는 잠재 이용자 규모입니다.':'노인복지시설의 주 이용 연령과 직접 연결되는 잠재 인구 규모입니다.';(found?selected:rejected).push({indicator:directLabel,role:'DEMAND',reason,source:found?'KOSIS DT_1B04006':null,referencePeriod,geographicResolution:found?'SIGUNGU':'UNKNOWN',coverage:new Set(verifiedMetrics.map(row=>row.regionCode)).size,status:found?'VERIFIED':'UNAVAILABLE',proxyStrength:'DIRECT'});if(!found)missing.push(directLabel);}
 else if(library){const found=verifiedMetrics.length>1;(found?selected:rejected).push({indicator:'총인구',role:'CONTEXT',reason:'공공도서관 수를 인구 규모가 다른 지역 간 비교하기 위한 분모입니다. 도서관 직접 수요로 사용하지 않습니다.',source:found?'KOSIS DT_1B04006':null,referencePeriod,geographicResolution:found?'SIGUNGU':'UNKNOWN',coverage:new Set(verifiedMetrics.map(row=>row.regionCode)).size,status:found?'VERIFIED':'UNAVAILABLE',proxyStrength:'INDIRECT'});}
 else rejected.push({...unavailable('총인구','CONTEXT','시설 특성과 직접 연결되는 수요를 설명하기에 지나치게 일반적이므로 지역 선정에서 제외합니다.'),source:'KOSIS DT_1B04006',proxyStrength:'INDIRECT'});
 if(early){const found=supplyRows.length>1;(found?selected:rejected).push({indicator:'유아 천 명당 보육시설 수',role:'SUPPLY',reason:'0–5세 인구 대비 보육시설 공급 수준을 같은 단위로 비교합니다.',source:found?'KOSIS DT_1YL20951':null,referencePeriod:supplyRows.map(row=>row.source.period).filter(Boolean).sort().at(-1)??null,geographicResolution:found?'SIGUNGU':'UNKNOWN',coverage:supplyRows.length,status:found?'VERIFIED':'UNAVAILABLE',proxyStrength:'DIRECT'});if(!found)missing.push('시군구별 보육시설 공급 수준');}
 else if(library){const found=supplyRows.length>1;(found?selected:rejected).push({indicator:'공공도서관 수',role:'SUPPLY',reason:'전국도서관표준데이터에서 시군구별 공공도서관 목록을 집계한 시설 공급 지표입니다.',source:found?'공공데이터포털 전국도서관표준데이터':null,referencePeriod:supplyRows.map(row=>row.source.period).filter(Boolean).sort().at(-1)??null,geographicResolution:found?'SIGUNGU':'UNKNOWN',coverage:supplyRows.length,status:found?'PARTIAL':'UNAVAILABLE',proxyStrength:'DIRECT'});if(!found)missing.push('시군구별 공공도서관 공급');}
 else {missing.push(`${profile.facilityName} 시군구별 공급 지표`);rejected.push(unavailable(`${profile.facilityName} 시설 공급`,'SUPPLY','검증된 시군구 비교 데이터가 현재 연결되어 있지 않습니다.'));}
 const hasDirect=selected.some(row=>row.proxyStrength==='DIRECT'),hasSupply=selected.some(row=>row.role==='SUPPLY'),valid=early?hasDirect&&hasSupply:library?hasSupply&&selected.some(row=>row.indicator==='총인구'):hasDirect;
 return {facility:profile.facilityName,planningQuestion:early?'영유아 인구 규모와 보육시설 공급 수준 사이의 지역 불일치는 어디에서 나타나는가?':library?'인구 규모를 고려했을 때 공공도서관 공급 수준이 낮아 추가 조사가 필요한 지역은 어디인가?':`${profile.facilityName}의 시설 특성과 직접 연결되는 시군구 수요·공급 지표를 확보할 수 있는가?`,demandDimensions:directLabel?[directLabel]:[],supplyDimensions:early?['유아 천 명당 보육시설 수']:library?['공공도서관 수']:[],mismatchHypotheses:early?['높은 0–5세 인구 · 낮은 유아 인구 대비 보육시설 공급']:library?['인구 대비 공공도서관 공급 수준이 낮음']:[],selectedIndicators:selected,rejectedIndicators:rejected,missingIndicators:missing,selectionRules:early?['수요 상위 25%와 공급 하위 25%를 각각 비교','숨은 가중치 없이 수요·공급 유형으로 분류']:library?['총인구는 시설 수의 비교 분모로만 사용','인구 10만 명당 공공도서관 공급 하위 지역을 연구 후보로 분류']:[],limitations:valid?(library?['표준데이터 행별 기준일과 운영 상태가 완전히 일치하지 않아 공급 자료는 PARTIAL입니다.']:[]):['시설 특성과 직접 연결되는 시군구 단위 지표가 충분히 확보되지 않았습니다.'],status:valid?'VALID':'INSUFFICIENT_SELECTION_BASIS'};
}
