import {useState} from 'react';
import type {RegionEvidenceProfile} from '../../services/geography/types';
import {dimensionLabels} from '../../services/regional/config';
import {GeographicEvidenceList,evidenceTypeLabels} from '../GeographicOverview/EvidenceList';
export function RegionalEvidenceDetail({region}:{region:RegionEvidenceProfile}){
 const assessment=region.regionalAssessment!;const [category,setCategory]=useState('all');
 const source=(ids:string[])=>region.evidenceItems.filter(i=>ids.includes(i.id)&&(category==='all'||i.categories.includes(category as keyof typeof evidenceTypeLabels)));
 return <section className="detail-section regional-detail" aria-labelledby="detail-title"><div className="section-heading"><div><span className="section-kicker">REGIONAL EVIDENCE DETAIL</span><h2 id="detail-title">{region.region.displayName}</h2></div><span className={`mode-badge ${region.mode}`}>{region.mode.toUpperCase()} · {assessment.status}</span></div>
  <h3>왜 이 지역이 지도에 표시되었는가?</h3><p>선택 이슈: {assessment.issueTitle}</p><p>{assessment.eligible?`이 이슈의 검증 항목에 연결된 시·군·구 직접 근거 ${assessment.directEvidenceIds.length}건이 있습니다.`:'발견·맥락 자료만 보존한 지역입니다. 지도 이슈 표시 대상이 아닙니다.'}</p>
  <h3>지역 현상과 근거 범위</h3><div className="regional-table-wrap"><table><thead><tr><th>검증 차원</th><th>직접 근거</th><th>근거 수</th></tr></thead><tbody>{Object.entries(assessment.evidenceCoverage).map(([dimension,value])=><tr key={dimension}><th>{dimensionLabels[dimension as keyof typeof dimensionLabels]}</th><td>{value.status==='available'?'✓ 확인':value.status==='partial'?'△ 맥락·미검증':'✕ 데이터 부족'}</td><td>{value.evidenceIds.length}</td></tr>)}</tbody></table></div>
  <details><summary>지역 현상 원문과 행정 단위</summary>{assessment.links.map((link,index)=><article key={index}><strong>{link.administrativeLevel} · {link.geographicEvidenceRole} · {link.dataKind}</strong><blockquote>{link.quote}</blockquote><p>{link.reason}</p><a href={`#regional-source-${link.evidenceId}`} onClick={()=>{const details=document.getElementById(`regional-source-${link.evidenceId}`)?.closest('details');if(details)details.open=true;}}>근거 원문 카드</a></article>)}</details>
  <dl className="analysis-stats"><div><dt>근거 범위</dt><dd>{assessment.coverageCount} / {assessment.coverageTotal}</dd></div><div><dt>Issue Signal</dt><dd>{assessment.issueSignal?.toFixed(1)??'N/A'}</dd></div><div><dt>Confidence</dt><dd>{region.confidence}</dd></div></dl>
  <details className="candidate-calculation panel"><summary>Issue Signal 계산과 출처</summary><p>평가 가능한 축의 동일 가중 평균입니다. 직접 근거 없는 지역은 N/A이며, 상반 자료는 보존하고 확신도를 낮춥니다.</p>{Object.entries(assessment.scoreDimensions).map(([key,d])=><div key={key}><strong>{key} · {d.score?.toFixed(1)??'미평가'}</strong><p>{d.reason}</p>{d.evidenceIds.map(id=>{const item=region.evidenceItems.find(i=>i.id===id);return item?.url?<a key={id} href={item.url} target="_blank" rel="noopener noreferrer">{item.title} ↗ </a>:<span key={id}>{id} · DEMO </span>;})}</div>)}<p>{assessment.scoreCalculation.weightedSum.toFixed(2)} ÷ {assessment.scoreCalculation.weightSum} → {assessment.issueSignal??'N/A'}</p><p>반복 출처·유형의 기여 상한 적용. 원래 자료는 모두 보존합니다.</p><ul>{region.confidenceReasons.map(reason=><li key={reason}>{reason}</li>)}</ul></details>
  <h3>지역 지표</h3>{assessment.regionalMetrics.length?assessment.regionalMetrics.map(m=><article key={m.metricId}><strong>{m.metricType} · {m.value??'N/A'} {m.unit}</strong><p>{m.regionName} · {m.administrativeLevel} · {m.referenceDate??'기준 시점 미확인'} · {m.comparable?'비교 그룹 확인':'비교 불가'}</p><p>{m.definition} · 모집단: {m.populationDefinition??'미확인'} · 분모: {m.denominator??'미확인'}</p><p>{m.limitations.join(' ')}</p>{m.sourceUrl&&<a href={m.sourceUrl} target="_blank" rel="noopener noreferrer">원문 {m.sourceLocator} ↗</a>}</article>):<p>직접 검증된 지역 지표가 없습니다.</p>}
  {assessment.derivedIndicators.map((d,index)=><article key={index}><strong>{d.indicator}: {d.result.toFixed(3)}</strong><p>{d.formula} · 기준 {d.referenceYears.join(' / ')}</p><details><summary>입력 지표·출처</summary><p>{d.inputs.join(' / ')}</p><p>{d.sourceEvidenceIds.join(' / ')}</p></details></article>)}
  <div className="region-category-controls"><label htmlFor="regional-detail-category">근거 유형</label><select id="regional-detail-category" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">전체</option>{Object.entries(evidenceTypeLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><span>표시만 필터링하며 점수는 바뀌지 않습니다.</span></div>
  <section className="region-evidence-group conflict"><h3>상충·주의 근거</h3><GeographicEvidenceList items={source(assessment.conflictingEvidenceIds)} emptyMessage="판정된 상반 자료가 없습니다. 미판정은 상충 없음이 아닙니다."/></section>
  <section className="region-evidence-group"><h3>지역 직접 근거</h3><GeographicEvidenceList items={source(assessment.directEvidenceIds)}/></section>
  <section className="region-evidence-group"><h3>상위 지역 맥락 · PARENT_CONTEXT</h3><GeographicEvidenceList items={source(assessment.parentContextEvidenceIds)}/></section>
  <section className="region-evidence-group"><h3>전국 맥락 · NATIONAL_CONTEXT</h3><GeographicEvidenceList items={source(assessment.nationalContextEvidenceIds)}/></section>
  <aside className="geographic-warning"><h3>데이터 부족과 비교 한계</h3><ul>{assessment.dataGaps.map((gap,index)=><li key={index}>{gap.message}</li>)}{assessment.limitations.map(l=><li key={l}>{l}</li>)}</ul></aside>
  <details><summary>보존한 원문 출처 전체</summary>{region.evidenceItems.map(item=><div key={item.id} id={`regional-source-${item.id}`}><GeographicEvidenceList items={[item]}/></div>)}</details>
 </section>;
}
