import {structuredPhenomenonGraph} from '../../services/issues/structuredIssues';
import type {RegionEvidenceProfile} from '../../services/geography/types';
export function SigunguDetail({region}:{region:RegionEvidenceProfile}){
 const graph=structuredPhenomenonGraph(region);
 return <section className="panel sigungu-detail"><h3>{region.region.displayName} · 시군구 상세</h3><p>정규 코드 {region.region.regionCode} · 근거 상태 {region.facilityDataCoverage?.status} · Issue Signal {region.candidateScore??'N/A'}</p>
 <h4>수요 측 · 잠재 이용자 인구 신호</h4>{region.demographicMetrics?.length?region.demographicMetrics.map(m=><details key={m.metricId}><summary>{m.metricType} · {m.value??'N/A'} {m.unit} · {m.referenceDate} · {m.dataMode}</summary><p>기간 {m.periodStart??m.referenceDate} ~ {m.periodEnd??m.referenceDate}</p><p>{m.limitations.join(' / ')}</p>{m.derivation&&<><p>식: {m.derivation.formula}</p><p>입력: {m.derivation.inputMetricIds.join(' / ')}</p></>}<p>출처 {m.structuredSource?.provider} 국가통계포털 · 기관 {m.structuredSource?.organizationId} · {m.structuredSource?.tableName} / {m.structuredSource?.tableId}</p><p>항목 {m.structuredSource?.itemId} · 제공자 지역 코드 {m.structuredSource?.providerRegionCode} · 수신 시각 {m.structuredSource?.retrievedAt}</p><p>분류·시점 {m.sourceLocator}</p><a href={m.sourceUrl!} target="_blank" rel="noopener noreferrer">공식 출처</a><pre>{JSON.stringify(m.structuredSource?.rawSource,null,2)}</pre></details>):<p>총인구·대상인구·비율·변화: NO DATA</p>}
 <h4>전국 비교 가능한 시군구 내 상대 위치</h4>{region.demographicPositions?.length?region.demographicPositions.map(p=><p key={p.cohortId}>{p.metric} · {p.percentile.toFixed(1)} 백분위 · 비교 지역 {p.comparisonPopulation}개 · {p.referencePeriod}<br/>{p.method}</p>):<p>동일 조건의 비교 집단 없음 · N/A</p>}
 <h4>공급 측</h4>{region.facilitySupplyMetrics?.length?region.facilitySupplyMetrics.map(m=><details key={m.metricId}><summary>{m.metricType} · {m.value??'N/A'} {m.unit} · {m.dataMode} · {m.referenceDate??'기준일 미확인'}</summary><p>{m.definition}</p><p>원본 {m.sourceRecordCount} / 채택 {m.filteredRecordCount} / 제외 {m.excludedRecordCount}</p><p>{m.limitations.join(' / ')}</p>{m.formula&&<p>{m.formula} · 입력 {m.inputMetricIds?.join(' / ')}</p>}<p>시설 ID: {m.sourceRecordIds.join(' / ')}</p><a href={m.sourceUrl} target="_blank" rel="noopener noreferrer">공식 공급 데이터</a></details>):<p>시설 수·정원·현원: NO DATA</p>}<p>시설 공급 변화 데이터 미연결</p>
 <h4>수요·공급 지표의 상대 위치</h4>{region.supplyRelativePositions?.length?region.supplyRelativePositions.map(p=><p key={p.indicatorId}>{p.type} · 원값 {p.rawValue.toFixed(3)} · {p.percentile.toFixed(1)} 백분위 · 비교 지역 {p.cohortSize}개 · {p.referencePeriod}</p>):<p>동일 시점·정의의 비교 집단 없음 · N/A</p>}
 <h4>공급 데이터 품질</h4>{region.facilityDataQuality?.map((q,i)=><pre key={i}>{JSON.stringify(q,null,2)}</pre>)}
 <h4>관계</h4><p>입력 호환성: {region.demandSupplyCompatibility?.status??'UNKNOWN'}</p>{region.demandSupplyIndicators?.length?region.demandSupplyIndicators.map(m=><details key={m.id}><summary>{m.type} · {m.value.toFixed(3)} {m.unit}</summary><p>{m.formula}</p><p>{m.inputMetricIds.join(' / ')}</p>{m.sourceUrls.map((url,i)=><a key={i} href={url} target="_blank" rel="noopener noreferrer">입력 출처 {i+1} </a>)}</details>):<p>동일 시군구·기준일·정의의 비율 입력 부족: N/A</p>}
 <h4>이 데이터가 의미하는 현상</h4>{region.demographicPhenomena?.map(p=><p key={p.id}>{p.description}</p>)}{region.demandSupplyRelationships?.map(r=><details key={r.id}><summary>{r.type}</summary><p>{r.description}</p><p>{r.inputMetricIds.join(' / ')}</p></details>)}<p>잠재 이용자와 시설 공급을 비교하는 탐색 자료입니다. 시설 부족이나 신축·최종 부지를 판정하지 않습니다.</p>
 <h4>왜 이 시군구인가 · 건축 이슈와 근거 경로</h4>{graph.issues.length?graph.issues.map(issue=><details key={issue.id}><summary>{issue.title}</summary><p>{issue.summary}</p><p>{issue.architecturalRelevance}</p><p>관계: {issue.relationshipIds.join(' / ')}</p><p>현상: {issue.phenomenonIds.join(' / ')}</p><p>원본 입력 지표: {issue.evidenceIds.join(' / ')}</p></details>):<p>건축 이슈를 뒷받침할 검증된 수요·공급 변화 관계가 아직 없습니다.</p>}
 <h4>한계</h4><ul>{[...new Set(region.facilityDataGaps)].map(g=><li key={g}>{g}</li>)}</ul>
 <details><summary>원본 시설 기록 {region.facilityRecords?.length??0}개</summary>{region.facilityRecords?.map((r,i)=><details key={`${r.providerFacilityId}:${i}`}><summary>{r.facilityName} · {r.status} · {r.normalizationStatus}</summary><p>수신 {r.retrievedAt}</p><pre>{JSON.stringify(r.rawSource,null,2)}</pre></details>)}</details>
 </section>;
}
